### ISSUE TITLE
Some labels are not exported from Crowdin to localize.typo3.org

### ISSUE THREAD

**Issue by peterkraume** [TYPO3/crowdin-bridge#12]
There are labels which are not exported from Crowdin to the zip files which are stored on localize.typo3.org.

Example:
- Identifier (Key): `pages.canonical_link.description`
- Source XLF File: `EXT:seo/Resources/Private/Language/locallang_tca.xlf`
- Crowdin translation: https://crowdin.com/editor/typo3-cms/1172/en-de?view=comfortable&filter=basic&value=3#q=pages.canonical_link.description

In the ZIP file the mentioned identifier ist missing:
https://localize.typo3.org/xliff/s/e/seo-l10n/seo-l10n-de.v12.zip

When you download the ZIP file which is built by Crowdin directly, the translation can be found in `main/typo3/sysext/seo/Resources/Private/Language/de.locallang_tca.xlf` 

The language label `pages.canonical_link.description` was introduced with this commit:
https://github.com/TYPO3/typo3/commit/79683d6f84c0837cc037bf382f67313af1a82e93

The first version of TYPO3 containing that label was 12.4.6:
https://get.typo3.org/release-notes/12.4.6

The label is included in TYPO3 13.1.0. The problem therefore "only" affects TYPO3 v12.

I assume the problem is within our Crowdin Bridge. Maybe the problem is, that the new label was introduced after the official LTS release?

**Comment by georgringer** [comment]
can you conform that the label is now there? didn't change yet anything but also works in v3 locally

**Comment by peterkraume** [comment]
Yes, the label is now available in https://localize.typo3.org/xliff/s/e/seo-l10n/seo-l10n-de.v12.zip
